//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPANY_db_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_items
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Project_Id { get; set; }
        public long Employee_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public System.DateTime DateDue { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual projects projects { get; set; }
    }
}
